version: 2
jobs:
  build:
    working_directory: ~/beagle-repository

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      # enable docker in docker
      - setup_remote_docker

      # Prepare the e2e image
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # Build image
      - run: |
          export DOCKERHUB_TAG=${CIRCLE_BRANCH/\//-}-${CIRCLE_BUILD_NUM}
          case "${CIRCLE_BRANCH}" in
              master)
                echo "Building docker image with tag ${DOCKERHUB_TAG} and latest."
                docker build -t keybird/beagle-e2e:${DOCKERHUB_TAG} .
                docker tag keybird/beagle-e2e:${DOCKERHUB_TAG} keybird/beagle-e2e:latest
                docker push keybird/beagle-e2e:${DOCKERHUB_TAG}
                docker push keybird/beagle-e2e:latest
                ;;
              *)
                echo "Building docker image with tag ${DOCKERHUB_TAG}."
                docker build -t keybird/beagle-e2e:${DOCKERHUB_TAG} .
                docker push keybird/beagle-e2e:${DOCKERHUB_TAG}
                ;;
            esac